const Data = [
    {
      id: "1",
      title: "Hanuman Ji",
      category: "Sketch",
      price: "$1",
      DateModified: "2019-11-14T10:18:51Z",
      img: "./images/HanumanJi.jpeg",
      desc: " Poha. Light, filling  And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "2",
      title: "Shiv Ji",
      category: "Painting",
      price: "$1",
      DateModified: "2018-11-14T10:18:51Z",
      img: "./images/shivJi.jpeg",
      desc: " A quintessential this recipe makes for a hearty morning meal. With some grated coconut on top, it gives a beautiful  flavour.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "3",
      title: "Landscape",
      category: "Painting",
      price: "$1",
      DateModified: "2020-11-14T10:18:51Z",
      img: "./images/Landscape.jpeg",
      desc: "A staple across One such delicacy is moong dal cheela. You can also add paneer to this recipe to amp up the nutritional value and make it, even more, protein-dense",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "4",
      title: "Adah Sharma",
      category: "Sketch",
      price: "$1",
      DateModified: "2021-11-14T10:18:51Z",
      img: "./images/adahSharma.jpeg",
      desc: "A classic  ginger, coriander powder, carom powder, and some mango powder, which is what gives the chana its sour and tangy taste.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "5",
      title: "Virat Kohli",
      category: "Sketch",
      price: "$1",
      DateModified: "2022-11-14T10:18:51Z",
      img: "./images/viratKohli.jpeg",
      desc: " fojj ivv jhv  jidfjv lorem  gijvv ovkv k methi, fresh cream, yogurt, and fresh coriander.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "6",
      title: "Malika Singh",
      category: "Sketch",
      price: "$1",
      DateModified: "2023-11-14T10:18:51Z",
      img: "./images/malikaSingh.jpeg",
      desc: "Don't get intimidated also because all they'll need is 20 minutes of your time. Chunks of cottage cheese cooked in some exciting spices, yogurt and a pinch of sugar.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "7",
      title: "Shree Ram",
      category: "Sketch",
      price: "$1",
      DateModified: "2024-11-14T10:18:51Z",
      img: "./images/shreeRam.jpeg",
      desc: "Get your daily dose of perfect protein. jk in s kf id asdfg hieo jd0 ving it a unique touch.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "8",
      title: "Shree Ram",
      category: "Painting",
      price: "$1",
      DateModified: "2017-11-14T10:18:51Z",
      img: "./images/shreeRam2.jpeg",
      desc: "Your family will thank you for this fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions, and some ghee.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "9",
      title: "Shree Krishna",
      category: "Painting",
      price: "$1",
      DateModified: "2016-11-14T10:18:51Z",
      img: "./images/shreeKrishna.jpeg",
      desc: "A rich velvet will leave you licking your fingers. Makhmali kofte can be your go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "10",
      title: "Commision Work1",
      category: "Commision Work",
      price: "$1",
      DateModified: "2015-11-14T10:18:51Z",
      img: "./images/commisionWork1.jpeg",
      desc: "A rich gravy  go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "11",
      title: "Commision Work2",
      category: "Commision Work",
      price: "$1",
      DateModified: "2015-11-14T10:18:51Z",
      img: "./images/commisionWork2.jpeg",
      desc: "A rich gravy go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "12",
      title: "Devendra",
      category: "Sketch",
      price: "$1",
      DateModified: "2015-11-14T10:18:51Z",
      img: "./images/devendra.jpeg",
      desc: "A rich gravy ur go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "13",
      title: "Eye 1",
      category: "Sketch",
      price: "$1",
      DateModified: "2015-11-14T10:18:51Z",
      img: "./images/eye1.jpeg",
      desc: "A rich gravy ur go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
    {
      id: "14",
      title: "Eye2",
      category: "Sketch",
      price: "$1",
      DateModified: "2015-11-14T10:18:51Z",
      img: "./images/eye2.jpeg",
      desc: "A rich gravy  go-to dish for dinner parties as this is quite different from other kofta recipes and extremely delicious.",
      LargeDesc: "The poet sees different sceneries while travelling by train. He sees bridges, houses, ditches and hedges. Meadows, where horses and cattle are gazing, hills, plains and painted buildings of railway stations can be seen. The poet also sees a child climbing up a steep ground collecting blackberries, a homeless man standing and watching as the train passes by, village women making garland out of daisies, a cart moving laboriously on the highway with the weight of the load and a man on it. He also sees a mill and rivers. They all pass by very quickly, disappearing as fast as they appeared.",
    },
  ];
   
  export default Data;